//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGitHub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBPickiuEntities : DbContext
    {
        public DBPickiuEntities()
            : base("name=DBPickiuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ciudades> Ciudades { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Fincas> Fincas { get; set; }
        public virtual DbSet<Flores> Flores { get; set; }
        public virtual DbSet<Guias> Guias { get; set; }
        public virtual DbSet<Paises> Paises { get; set; }
        public virtual DbSet<Pickiu> Pickiu { get; set; }
        public virtual DbSet<Siglas> Siglas { get; set; }
        public virtual DbSet<Vuelos> Vuelos { get; set; }
        public virtual DbSet<Origenes> Origenes { get; set; }
    }
}
