//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Origenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Origenes()
        {
            this.Pickiu = new HashSet<Pickiu>();
        }
    
        public int id { get; set; }
        public int idPais { get; set; }
        public int idCiudad { get; set; }
        public int idFinca { get; set; }
        public Nullable<int> idSigla { get; set; }
    
        public virtual Ciudades Ciudades { get; set; }
        public virtual Fincas Fincas { get; set; }
        public virtual Paises Paises { get; set; }
        public virtual Siglas Siglas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pickiu> Pickiu { get; set; }
    }
}
