//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pickiu
    {
        public int id { get; set; }
        public int idGuia { get; set; }
        public int idFlor { get; set; }
        public int Cantidad { get; set; }
        public int idOrigen { get; set; }
    
        public virtual Flores Flores { get; set; }
        public virtual Guias Guias { get; set; }
        public virtual Origenes Origenes { get; set; }
    }
}
