//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaGitHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siglas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siglas()
        {
            this.Origenes = new HashSet<Origenes>();
        }
    
        public int id { get; set; }
        public string Sigla { get; set; }
        public int idFinca { get; set; }
    
        public virtual Fincas Fincas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Origenes> Origenes { get; set; }
    }
}
